name: CI
run-name: Deploy
on: push
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install npm deps
      run: npm i
    - name: Run linter
      run: npm run check
    - name: Start app
      run: npm start
